### ISSUE TITLE
摘要前后有空页

### ISSUE THREAD

**Issue by heihei12305** [obster-y/NCEPU-thesis#3]
中文和英文的摘要前后都有空页, 当前的demo pdf就是这样

**Comment by obster-y** [comment]
1. 准确地说，是「封面后、中英摘要后有空白页」
2. 是的，空白页是因为考虑到要进行双面打印，确保封面、摘要在奇数页
3. 这个问题已经在[刚刚的commit](https://github.com/obster-y/NCEPU-thesis/commit/bf4d961d81c6373b1bd87834941d9df48279975c)进行了修复，现在可以通过更改文档类的参数「oneside」或「twoside」进行设置 

> 
> 
> 中文和英文的摘要前后都有空页, 当前的demo pdf就是这样
