### ISSUE TITLE
Linux 平台下\zhdigits{0}字符〇无法正常显示（被替换为空白字符）

### ISSUE THREAD

**Issue by Raibows** [obster-y/NCEPU-thesis#6]
字符**〇**会使用在封面日期上。
定位问题在cls文件59-89行的平台判断，字体选择上
https://github.com/obster-y/NCEPU-thesis/blob/fdfb99d11ad08ce63c04236483c77101b7088360/NCEPU-thesis.cls#L59-L89

似乎Linux的字体选择和windows不一致，字符集貌似不包含字符**〇**。经我个人尝试，Linux上直接使用Windows上的配置可正确工作。

附上版本做参考，还有待确认：
Linux version：Ubuntu 20.04.2
XeTeX 3.14159265-2.6-0.999991 (TeX Live 2019/Debian)

**Comment by obster-y** [comment]
已确认，方正宋体 fzsong.ttf 涵盖的字符集较少，包括`〇`等，确实用 win 的配置可行，已修改
